export type ApiErrorCode =
  | "VALIDATION_ERROR"
  | "INVALID_CREDENTIALS"
  | "INVALID_SESSION"
  | "USER_DISABLED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "REGISTRATION_FAILED"
  | "RATE_LIMITED"
  | "SERVICE_UNAVAILABLE"
  | "HTTP_ERROR"
  | "INTERNAL_ERROR"
  | "USER_NOT_FOUND"
  | "INVALID_ROLE"
  | "USER_ALREADY_DISABLED"
  | "USER_ALREADY_ACTIVE"
  | "ROLE_UNCHANGED"
  | "CANNOT_DISABLE_SELF"
  | "CANNOT_MODIFY_SELF_ROLE"
  | "LAST_ADMIN_PROTECTION"
  | "CATALOG_ACTIVATION_BLOCKED"
  | "PRODUCT_STATUS_UNCHANGED"
  | "VARIANT_STATUS_UNCHANGED"
  | "CATALOG_MASTER_CONFLICT"
  | "INVENTORY_VARIANT_NOT_FOUND"
  | "INVENTORY_WAREHOUSE_NOT_FOUND"
  | "INVENTORY_NOOP"
  | "INVENTORY_TARGET_BELOW_RESERVED"
  | "INVENTORY_WAREHOUSE_UNAVAILABLE"
  | "INVENTORY_INSUFFICIENT"
  | "CART_EMPTY"
  | "CART_ITEM_NOT_FOUND"
  | "CART_QUANTITY_INVALID"
  | "CART_QUANTITY_LIMIT_EXCEEDED"
  | "VARIANT_NOT_FOUND"
  | "VARIANT_NOT_SELLABLE"
  | "OUT_OF_STOCK"
  | "INSUFFICIENT_AVAILABLE_STOCK"
  | "CART_CONFLICT"
  | "SHIPPING_QUOTE_STALE"
  | "INVALID_ORDER_TRANSITION"
  | "ORDER_TRANSITION_CONFLICT"
  | "ORDER_NOT_FOUND"
  | "PAID_ORDER_CANNOT_CANCEL"
  | "STOCK_RESERVATION_INCONSISTENT"
  // Promotion / Coupon
  | "COUPON_INVALID"
  | "COUPON_NOT_FOUND"
  | "COUPON_DISABLED"
  | "COUPON_NOT_STARTED"
  | "COUPON_EXPIRED"
  | "COUPON_MIN_ORDER_NOT_MET"
  | "COUPON_USAGE_LIMIT_REACHED"
  | "COUPON_USER_LIMIT_REACHED"
  | "COUPON_INVALID_VALUE"
  | "COUPON_CODE_CONFLICT"
  | "COUPON_IMMUTABLE_AFTER_USAGE"
  // Review
  | "REVIEW_NOT_ELIGIBLE"
  | "REVIEW_ALREADY_EXISTS"
  | "REVIEW_NOT_FOUND"
  // Reporting
  | "REPORT_INVALID_DATE_RANGE"
  | "REPORT_RANGE_TOO_LARGE"
  | "REPORT_INVALID_GRANULARITY"
  | "REPORT_INVALID_GROUP_BY"
  | "REPORT_INVALID_SORT"
  | "REPORT_QUERY_FAILED"
  // Payment & VNPay
  | "VNPAY_CONFIG_INVALID"
  | "VNPAY_SIGNATURE_INVALID"
  | "VNPAY_AMOUNT_MISMATCH"
  | "VNPAY_TXN_REF_NOT_FOUND"
  | "VNPAY_TRANSACTION_CONFLICT"
  | "VNPAY_PAYMENT_ALREADY_COMPLETED"
  | "VNPAY_PROVIDER_ERROR"
  | "VNPAY_CALLBACK_INVALID"
  | "PAYMENT_INVALID_STATE"
  | "PAYMENT_URL_CREATE_FAILED"
  | "PAYMENT_EXPIRED"
  | "REFUND_NOT_SUPPORTED"
  // Shipping & GHN
  | "SHIPPING_PROVIDER_UNAVAILABLE"
  | "GHN_AUTH_FAILED"
  | "GHN_ADDRESS_MAPPING_FAILED"
  | "GHN_SERVICE_NOT_AVAILABLE"
  | "GHN_QUOTE_FAILED"
  | "GHN_CREATE_SHIPMENT_FAILED"
  | "GHN_SHIPMENT_NOT_FOUND"
  | "GHN_INVALID_RESPONSE"
  | "SHIPPING_TIMEOUT"
  | "SHIPPING_ALREADY_CREATED"
  | "SHIPPING_STATUS_INVALID"
  | "SHIPMENT_NOT_READY"
  // Tax & Invoice
  | "INVOICE_NOT_FOUND"
  | "INVOICE_ALREADY_ISSUED"
  | "INVOICE_VOIDED"
  | "TAX_RATE_INVALID"
  | "TAX_CONFIG_MISSING"
  // Email & Password Reset
  | "PASSWORD_RESET_TOKEN_INVALID"
  | "PASSWORD_RESET_TOKEN_EXPIRED"
  | "PASSWORD_RESET_OTP_INVALID"
  | "PASSWORD_RESET_TOO_MANY_ATTEMPTS"
  | "MAIL_CONFIG_INVALID"
  | "MAIL_SEND_FAILED"
  | "EMAIL_NOT_VERIFIED"
  | "EMAIL_VERIFICATION_TOKEN_INVALID"
  | "EMAIL_VERIFICATION_TOKEN_EXPIRED"
  | "EMAIL_ALREADY_VERIFIED"
  // Reporting Excel Export
  | "REPORT_EXPORT_FAILED"
  | "REPORT_EXPORT_TOO_LARGE"
  | "REPORT_EXPORT_UNSUPPORTED_TYPE"
  | "WEBHOOK_UNAUTHORIZED";

export type ApiErrorDetail = {
  field: string;
  message: string;
};

export type ApiError = {
  statusCode: number;
  code: ApiErrorCode;
  message: string;
  details?: ApiErrorDetail[];
  requestId?: string;
};

const API_ERROR_CODES = new Set<ApiErrorCode>([
  "VALIDATION_ERROR",
  "INVALID_CREDENTIALS",
  "INVALID_SESSION",
  "USER_DISABLED",
  "FORBIDDEN",
  "NOT_FOUND",
  "REGISTRATION_FAILED",
  "RATE_LIMITED",
  "SERVICE_UNAVAILABLE",
  "HTTP_ERROR",
  "INTERNAL_ERROR",
  "USER_NOT_FOUND",
  "INVALID_ROLE",
  "USER_ALREADY_DISABLED",
  "USER_ALREADY_ACTIVE",
  "ROLE_UNCHANGED",
  "CANNOT_DISABLE_SELF",
  "CANNOT_MODIFY_SELF_ROLE",
  "LAST_ADMIN_PROTECTION",
  "CATALOG_ACTIVATION_BLOCKED",
  "PRODUCT_STATUS_UNCHANGED",
  "VARIANT_STATUS_UNCHANGED",
  "CATALOG_MASTER_CONFLICT",
  "INVENTORY_VARIANT_NOT_FOUND",
  "INVENTORY_WAREHOUSE_NOT_FOUND",
  "INVENTORY_NOOP",
  "INVENTORY_TARGET_BELOW_RESERVED",
  "INVENTORY_WAREHOUSE_UNAVAILABLE",
  "INVENTORY_INSUFFICIENT",
  "CART_EMPTY",
  "CART_ITEM_NOT_FOUND",
  "CART_QUANTITY_INVALID",
  "CART_QUANTITY_LIMIT_EXCEEDED",
  "VARIANT_NOT_FOUND",
  "VARIANT_NOT_SELLABLE",
  "OUT_OF_STOCK",
  "INSUFFICIENT_AVAILABLE_STOCK",
  "CART_CONFLICT",
  "SHIPPING_QUOTE_STALE",
  "INVALID_ORDER_TRANSITION",
  "ORDER_TRANSITION_CONFLICT",
  "ORDER_NOT_FOUND",
  "PAID_ORDER_CANNOT_CANCEL",
  "STOCK_RESERVATION_INCONSISTENT",
  "COUPON_INVALID",
  "COUPON_NOT_FOUND",
  "COUPON_DISABLED",
  "COUPON_NOT_STARTED",
  "COUPON_EXPIRED",
  "COUPON_MIN_ORDER_NOT_MET",
  "COUPON_USAGE_LIMIT_REACHED",
  "COUPON_USER_LIMIT_REACHED",
  "COUPON_INVALID_VALUE",
  "COUPON_CODE_CONFLICT",
  "COUPON_IMMUTABLE_AFTER_USAGE",
  "REVIEW_NOT_ELIGIBLE",
  "REVIEW_ALREADY_EXISTS",
  "REVIEW_NOT_FOUND",
  "REPORT_INVALID_DATE_RANGE",
  "REPORT_RANGE_TOO_LARGE",
  "REPORT_INVALID_GRANULARITY",
  "REPORT_INVALID_GROUP_BY",
  "REPORT_INVALID_SORT",
  "REPORT_QUERY_FAILED",
  "VNPAY_CONFIG_INVALID",
  "VNPAY_SIGNATURE_INVALID",
  "VNPAY_AMOUNT_MISMATCH",
  "VNPAY_TXN_REF_NOT_FOUND",
  "VNPAY_TRANSACTION_CONFLICT",
  "VNPAY_PAYMENT_ALREADY_COMPLETED",
  "VNPAY_PROVIDER_ERROR",
  "VNPAY_CALLBACK_INVALID",
  "PAYMENT_INVALID_STATE",
  "PAYMENT_URL_CREATE_FAILED",
  "PAYMENT_EXPIRED",
  "REFUND_NOT_SUPPORTED",
  "SHIPPING_PROVIDER_UNAVAILABLE",
  "GHN_AUTH_FAILED",
  "GHN_ADDRESS_MAPPING_FAILED",
  "GHN_SERVICE_NOT_AVAILABLE",
  "GHN_QUOTE_FAILED",
  "GHN_CREATE_SHIPMENT_FAILED",
  "GHN_SHIPMENT_NOT_FOUND",
  "GHN_INVALID_RESPONSE",
  "SHIPPING_TIMEOUT",
  "SHIPPING_ALREADY_CREATED",
  "SHIPPING_STATUS_INVALID",
  "SHIPMENT_NOT_READY",
  "INVOICE_NOT_FOUND",
  "INVOICE_ALREADY_ISSUED",
  "INVOICE_VOIDED",
  "TAX_RATE_INVALID",
  "TAX_CONFIG_MISSING",
  "PASSWORD_RESET_TOKEN_INVALID",
  "PASSWORD_RESET_TOKEN_EXPIRED",
  "PASSWORD_RESET_OTP_INVALID",
  "PASSWORD_RESET_TOO_MANY_ATTEMPTS",
  "MAIL_CONFIG_INVALID",
  "MAIL_SEND_FAILED",
  "EMAIL_NOT_VERIFIED",
  "EMAIL_VERIFICATION_TOKEN_INVALID",
  "EMAIL_VERIFICATION_TOKEN_EXPIRED",
  "EMAIL_ALREADY_VERIFIED",
  "REPORT_EXPORT_FAILED",
  "REPORT_EXPORT_TOO_LARGE",
  "REPORT_EXPORT_UNSUPPORTED_TYPE",
  "WEBHOOK_UNAUTHORIZED",
]);

export function isApiError(value: unknown): value is ApiError {
  if (!value || typeof value !== "object") {
    return false;
  }
  const candidate = value as Record<string, unknown>;
  return (
    typeof candidate.statusCode === "number" &&
    typeof candidate.code === "string" &&
    API_ERROR_CODES.has(candidate.code as ApiErrorCode) &&
    typeof candidate.message === "string" &&
    (candidate.requestId === undefined || typeof candidate.requestId === "string")
  );
}
